name: remote ssh command
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: "4.228.217.167"
        username: ${{ env.SSH_USER }}
        password: ${{ secrets.SSH_SECRET }}
        port: ${{ env.SSH_PORT }}
        script: whoami
